### ISSUE TITLE
Does not start to transcode

### ISSUE THREAD

**Issue by luttman** [cutzenfriend/docker-absautoconverter#1]
Hey!
i used your docker-compose.yml

version: '3.3'
services:
  abs-autoconverter:
    image: cutzenfriend/abs-autoconverter:latest
    container_name: abs-autoconverter
    restart: unless-stopped
    environment:
      TZ: "Europe/Berlin"
      DOMAIN: "***** Redracted ****" #Please edit - mandatory
      LIBRARY_ID: "***** Redracted ****" #Please edit - mandatory
      #MAX_PARALLEL_CONVERSIONS: 3 #Keep CPU power in mind. Too many conversion in parallel decrease performance on your host!
      CRON_SETTING: "30 * * * * "
      BITRATE: "128k" #optional - default is: 128k 
      TOKEN: ***** Redracted **** #Please edit - mandatory

it finds a book that needs to be edited but in the log it just stays at

Timezone is set to: Europe/Berlin
DOMAIN is set to: ***** Redracted ****
LIBRARY_ID is set to: ***** Redracted ****
MAX_PARALLEL_CONVERSIONS set to default 5
CRON_SETTING is set to: 30 * * * * 
TOKEN is set to: ***** Redracted ****
Bitrate for conversion ist set to default 128k
3/7/2024, 11:30:00 PM | Running next conversion | Converting the following Audiobooks to m4b:
3/8/2024, 12:30:00 AM | Running next conversion | Converting the following Audiobooks to m4b:
3/8/2024, 1:30:00 AM | Running next conversion | Converting the following Audiobooks to m4b:
3/8/2024, 2:30:01 AM | Running next conversion | Converting the following Audiobooks to m4b:
3/8/2024, 3:30:01 AM | Running next conversion | Converting the following Audiobooks to m4b:
3/8/2024, 4:30:00 AM | Running next conversion | Converting the following Audiobooks to m4b:
3/8/2024, 5:30:00 AM | Running next conversion | Converting the following Audiobooks to m4b:
3/8/2024, 6:30:00 AM | Running next conversion | Converting the following Audiobooks to m4b:
3/8/2024, 7:30:00 AM | Running next conversion | Converting the following Audiobooks to m4b:

do i need to mount the path to the audiofiles?

**Comment by crazD802** [comment]
I had the same output and pulled my hair out only to find I had no tracks made up of multiple files...

**Comment by cutzenfriend** [comment]
> Hey! i used your docker-compose.yml
> 
> version: '3.3' services: abs-autoconverter: image: cutzenfriend/abs-autoconverter:latest container_name: abs-autoconverter restart: unless-stopped environment: TZ: "Europe/Berlin" DOMAIN: "***** Redracted **" #Please edit - mandatory LIBRARY_ID: "*** Redracted ****" #Please edit - mandatory #MAX_PARALLEL_CONVERSIONS: 3 #Keep CPU power in mind. Too many conversion in parallel decrease performance on your host! CRON_SETTING: "30 * * * * " BITRATE: "128k" #optional - default is: 128k TOKEN: ***** Redracted **** #Please edit - mandatory
> 
> it finds a book that needs to be edited but in the log it just stays at
> 
> Timezone is set to: Europe/Berlin DOMAIN is set to: ***** Redracted **** LIBRARY_ID is set to: ***** Redracted **** MAX_PARALLEL_CONVERSIONS set to default 5 CRON_SETTING is set to: 30 * * * * TOKEN is set to: ***** Redracted **** Bitrate for conversion ist set to default 128k 3/7/2024, 11:30:00 PM | Running next conversion | Converting the following Audiobooks to m4b: 3/8/2024, 12:30:00 AM | Running next conversion | Converting the following Audiobooks to m4b: 3/8/2024, 1:30:00 AM | Running next conversion | Converting the following Audiobooks to m4b: 3/8/2024, 2:30:01 AM | Running next conversion | Converting the following Audiobooks to m4b: 3/8/2024, 3:30:01 AM | Running next conversion | Converting the following Audiobooks to m4b: 3/8/2024, 4:30:00 AM | Running next conversion | Converting the following Audiobooks to m4b: 3/8/2024, 5:30:00 AM | Running next conversion | Converting the following Audiobooks to m4b: 3/8/2024, 6:30:00 AM | Running next conversion | Converting the following Audiobooks to m4b: 3/8/2024, 7:30:00 AM | Running next conversion | Converting the following Audiobooks to m4b:
> 
> do i need to mount the path to the audiofiles?

Sorry for the late answer but where do you see that it finds a book? If the script finds a book it prints the name.

**Comment by cutzenfriend** [comment]
No issues, just bad log texts :D
